---
language: python
python: "2.7"

sudo: required
dist: trusty
services:
- docker

env:
  matrix:
    - IMAGE_NAME="ubuntu18.04" PG_VERSION="10" ANSIBLE_VERSION="2.8.0"
    - IMAGE_NAME="ubuntu18.04" PG_VERSION="11" ANSIBLE_VERSION="2.8.0"
    - IMAGE_NAME="ubuntu18.04" PG_VERSION="12" ANSIBLE_VERSION="2.8.0"
    - IMAGE_NAME="ubuntu20.04" PG_VERSION="12" ANSIBLE_VERSION="2.9.0"
    - IMAGE_NAME="ubuntu20.04" PG_VERSION="13" ANSIBLE_VERSION="2.9.0"
    - IMAGE_NAME="debian9" PG_VERSION="11" ANSIBLE_VERSION="2.8.0"
    - IMAGE_NAME="debian9" PG_VERSION="13" ANSIBLE_VERSION="2.9.0"
#    - IMAGE_NAME="centos7" PG_VERSION="9.6" ANSIBLE_VERSION="2.8.0"
#    - IMAGE_NAME="centos7" PG_VERSION="11" ANSIBLE_VERSION="2.8.0"
#    - IMAGE_NAME="centos7" PG_VERSION="13" ANSIBLE_VERSION="2.9.0"

script:
  - docker build --build-arg PG_VERSION="$PG_VERSION" --build-arg ANSIBLE_VERSION="$ANSIBLE_VERSION" -f tests/Dockerfile-$IMAGE_NAME .

notifications:
webhooks: https://galaxy.ansible.com/api/v1/notifications/
