# file: postgresql/tasks/install_dnf_rh.yml

# The standard ca-certs are needed because  without them dnf will fail to
# validate www.postgresql.org (or probably any other source).

  - block:
      - name: PostgrSQL | Install all the required depedencies | dnf
        dnf:
          name: "ca-certificates, python3-pycurl, glibc-common, libselinux-python3, glibc-locale-source"
          state: present

      - name: PostgreSQL | Add yum Repository | dnf
        dnf:
          name: "{{ postgresql_dnf_rh_repository }}"
          state: present
        when: postgresql_install_repository

      - name: PostgreSQL | Disable default module | dnf
        command: "dnf -qy module disable postgresql"
        args:
          warn: False
        when: postgresql_install_repository

      - name: PostgreSQL | Install PostgreSQL | dnf
        dnf:
          name: ["postgresql{{ postgresql_version_terse }}-server", "postgresql{{ postgresql_version_terse }}", "postgresql{{ postgresql_version_terse }}-contrib"]
          state: present
        environment: "{{ postgresql_env }}"

      - name: PostgreSQL | PGTune | dnf
        dnf:
          name: pgtune
          state: present
        environment: "{{ postgresql_env }}"
        when: postgresql_pgtune
