# file: postgresql/tasks/users_privileges.yml

- name: PostgreSQL | Update the user privileges
  postgresql_privs:
    db: "{{ item.db | default(omit) }}"
    port: "{{ postgresql_port }}"
    priv: "{{ item.priv | default(omit) }}"
    state: present
    login_host: "{{ item.host | default(omit) }}"
    login_user: "{{ postgresql_admin_user }}"
    roles: "{{ item.name }}"
    schema: "{{ item.schema | default(omit) }}"
    objs: "{{ item.objs | default(omit) }}"
    type: "{{ item.type | default(table) }}"
    target_roles: "{{ item.target_roles | default(omit) }}"
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  with_items: "{{ postgresql_user_privileges }}"
  when: postgresql_users|length > 0
